name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --add-data "localisation.json;." --name "ShootersPool_Translator" main.py

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ShootersPool_Translator.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}